/** ISO 3166-1 alpha-2, E.164 country calling code, English name. Flags: flagcdn.com/w20/{iso}.png */
export type DialCountry = {
  iso: string;
  dial: string;
  name: string;
};

export const DIAL_COUNTRIES: DialCountry[] = [
  { iso: "AF", dial: "+93", name: "Afghanistan" },
  { iso: "AL", dial: "+355", name: "Albania" },
  { iso: "DZ", dial: "+213", name: "Algeria" },
  { iso: "AR", dial: "+54", name: "Argentina" },
  { iso: "AM", dial: "+374", name: "Armenia" },
  { iso: "AU", dial: "+61", name: "Australia" },
  { iso: "AT", dial: "+43", name: "Austria" },
  { iso: "AZ", dial: "+994", name: "Azerbaijan" },
  { iso: "BH", dial: "+973", name: "Bahrain" },
  { iso: "BD", dial: "+880", name: "Bangladesh" },
  { iso: "BY", dial: "+375", name: "Belarus" },
  { iso: "BE", dial: "+32", name: "Belgium" },
  { iso: "BO", dial: "+591", name: "Bolivia" },
  { iso: "BA", dial: "+387", name: "Bosnia and Herzegovina" },
  { iso: "BR", dial: "+55", name: "Brazil" },
  { iso: "BG", dial: "+359", name: "Bulgaria" },
  { iso: "KH", dial: "+855", name: "Cambodia" },
  { iso: "CM", dial: "+237", name: "Cameroon" },
  { iso: "CA", dial: "+1", name: "Canada" },
  { iso: "CL", dial: "+56", name: "Chile" },
  { iso: "CN", dial: "+86", name: "China" },
  { iso: "CO", dial: "+57", name: "Colombia" },
  { iso: "CR", dial: "+506", name: "Costa Rica" },
  { iso: "HR", dial: "+385", name: "Croatia" },
  { iso: "CY", dial: "+357", name: "Cyprus" },
  { iso: "CZ", dial: "+420", name: "Czech Republic" },
  { iso: "DK", dial: "+45", name: "Denmark" },
  { iso: "DO", dial: "+1", name: "Dominican Republic" },
  { iso: "EC", dial: "+593", name: "Ecuador" },
  { iso: "EG", dial: "+20", name: "Egypt" },
  { iso: "EE", dial: "+372", name: "Estonia" },
  { iso: "FI", dial: "+358", name: "Finland" },
  { iso: "FR", dial: "+33", name: "France" },
  { iso: "GE", dial: "+995", name: "Georgia" },
  { iso: "DE", dial: "+49", name: "Germany" },
  { iso: "GH", dial: "+233", name: "Ghana" },
  { iso: "GR", dial: "+30", name: "Greece" },
  { iso: "GT", dial: "+502", name: "Guatemala" },
  { iso: "HK", dial: "+852", name: "Hong Kong" },
  { iso: "HU", dial: "+36", name: "Hungary" },
  { iso: "IS", dial: "+354", name: "Iceland" },
  { iso: "IN", dial: "+91", name: "India" },
  { iso: "ID", dial: "+62", name: "Indonesia" },
  { iso: "IQ", dial: "+964", name: "Iraq" },
  { iso: "IE", dial: "+353", name: "Ireland" },
  { iso: "IL", dial: "+972", name: "Israel" },
  { iso: "IT", dial: "+39", name: "Italy" },
  { iso: "JM", dial: "+1", name: "Jamaica" },
  { iso: "JP", dial: "+81", name: "Japan" },
  { iso: "JO", dial: "+962", name: "Jordan" },
  { iso: "KZ", dial: "+7", name: "Kazakhstan" },
  { iso: "KE", dial: "+254", name: "Kenya" },
  { iso: "KR", dial: "+82", name: "South Korea" },
  { iso: "KW", dial: "+965", name: "Kuwait" },
  { iso: "LV", dial: "+371", name: "Latvia" },
  { iso: "LB", dial: "+961", name: "Lebanon" },
  { iso: "LY", dial: "+218", name: "Libya" },
  { iso: "LT", dial: "+370", name: "Lithuania" },
  { iso: "LU", dial: "+352", name: "Luxembourg" },
  { iso: "MY", dial: "+60", name: "Malaysia" },
  { iso: "MT", dial: "+356", name: "Malta" },
  { iso: "MX", dial: "+52", name: "Mexico" },
  { iso: "MD", dial: "+373", name: "Moldova" },
  { iso: "MA", dial: "+212", name: "Morocco" },
  { iso: "NL", dial: "+31", name: "Netherlands" },
  { iso: "NZ", dial: "+64", name: "New Zealand" },
  { iso: "NG", dial: "+234", name: "Nigeria" },
  { iso: "MK", dial: "+389", name: "North Macedonia" },
  { iso: "NO", dial: "+47", name: "Norway" },
  { iso: "OM", dial: "+968", name: "Oman" },
  { iso: "PK", dial: "+92", name: "Pakistan" },
  { iso: "PS", dial: "+970", name: "Palestine" },
  { iso: "PA", dial: "+507", name: "Panama" },
  { iso: "PE", dial: "+51", name: "Peru" },
  { iso: "PH", dial: "+63", name: "Philippines" },
  { iso: "PL", dial: "+48", name: "Poland" },
  { iso: "PT", dial: "+351", name: "Portugal" },
  { iso: "QA", dial: "+974", name: "Qatar" },
  { iso: "RO", dial: "+40", name: "Romania" },
  { iso: "RU", dial: "+7", name: "Russia" },
  { iso: "SA", dial: "+966", name: "Saudi Arabia" },
  { iso: "RS", dial: "+381", name: "Serbia" },
  { iso: "SG", dial: "+65", name: "Singapore" },
  { iso: "SK", dial: "+421", name: "Slovakia" },
  { iso: "SI", dial: "+386", name: "Slovenia" },
  { iso: "ZA", dial: "+27", name: "South Africa" },
  { iso: "ES", dial: "+34", name: "Spain" },
  { iso: "LK", dial: "+94", name: "Sri Lanka" },
  { iso: "SE", dial: "+46", name: "Sweden" },
  { iso: "CH", dial: "+41", name: "Switzerland" },
  { iso: "TW", dial: "+886", name: "Taiwan" },
  { iso: "TH", dial: "+66", name: "Thailand" },
  { iso: "TN", dial: "+216", name: "Tunisia" },
  { iso: "TR", dial: "+90", name: "Turkey" },
  { iso: "UA", dial: "+380", name: "Ukraine" },
  { iso: "AE", dial: "+971", name: "United Arab Emirates" },
  { iso: "GB", dial: "+44", name: "United Kingdom" },
  { iso: "US", dial: "+1", name: "United States" },
  { iso: "UY", dial: "+598", name: "Uruguay" },
  { iso: "UZ", dial: "+998", name: "Uzbekistan" },
  { iso: "VE", dial: "+58", name: "Venezuela" },
  { iso: "VN", dial: "+84", name: "Vietnam" },
].sort((a, b) => a.name.localeCompare(b.name));

export function dialCountryByIso(iso: string): DialCountry | undefined {
  return DIAL_COUNTRIES.find((c) => c.iso === iso);
}

/** Build E.164 from dial (e.g. +44) and national digits (no country code). */
export function toE164(dial: string, nationalDigits: string): string {
  const d = dial.replace(/\s/g, "");
  let n = nationalDigits.replace(/\D/g, "");
  if (n.startsWith("0") && n.length > 1) n = n.slice(1);
  if (!d.startsWith("+") || n.length < 6) return "";
  return `${d}${n}`;
}
